import { DependencyGraph, CircularCycle, OrphanNode } from '../graph/model';
import { CycleDetector } from '../graph/cycle';
import { OrphanDetector } from '../graph/orphan';

export class AuditReportGenerator {
  /**
   * Generates a comprehensive architectural audit report in Markdown
   */
  public static generateMarkdownReport(
    graph: DependencyGraph,
    cycles?: CircularCycle[],
    orphans?: OrphanNode[]
  ): string {
    const activeCycles = cycles || CycleDetector.detectCycles(graph);
    const activeOrphans = orphans || OrphanDetector.detectOrphans(graph);

    const totalNodes = Object.keys(graph.nodes).length;
    const totalEdges = graph.edges.length;

    // Count categories
    const categoryCounts: Record<string, number> = {};
    let totalLines = 0;
    for (const node of Object.values(graph.nodes)) {
      categoryCounts[node.category] = (categoryCounts[node.category] || 0) + 1;
      totalLines += node.lineCount || 0;
    }

    // Identify top hub files (most importedBy)
    const sortedHubs = Object.values(graph.nodes)
      .filter((n) => n.category !== 'other')
      .sort((a, b) => b.importedBy.length - a.importedBy.length)
      .slice(0, 8);

    const dateStr = new Date(graph.scannedAt || Date.now()).toLocaleString();

    let md = `# 🏗️ Atlas Architecture & Health Audit Report\n\n`;
    md += `> **Generated on:** ${dateStr}  \n`;
    md += `> **Workspace Root:** \`${graph.rootPath}\`  \n\n`;

    // 1. Executive Summary
    md += `## 1. Executive Summary\n\n`;
    md += `| Metric | Count | Status |\n`;
    md += `| :--- | :--- | :--- |\n`;
    md += `| **Total Source Files** | \`${totalNodes}\` | Scanned |\n`;
    md += `| **Total Dependency Links** | \`${totalEdges}\` | Indexed |\n`;
    md += `| **Total Lines of Code** | \`${totalLines.toLocaleString()}\` LOC | Tracked |\n`;
    md += `| **Circular Dependency Loops** | \`${activeCycles.length}\` | ${activeCycles.length === 0 ? '✅ Healthy (0 Cycles)' : '⚠️ Action Needed'} |\n`;
    md += `| **Potential Dead Code (Orphans)** | \`${activeOrphans.length}\` | ${activeOrphans.length === 0 ? '✅ Clean' : '🔍 Refactor Candidates'} |\n\n`;

    // 2. Architectural Composition
    md += `## 2. Architectural Layer Distribution\n\n`;
    md += `| Category | Files | Ratio |\n`;
    md += `| :--- | :--- | :--- |\n`;
    for (const [cat, count] of Object.entries(categoryCounts)) {
      const pct = totalNodes > 0 ? ((count / totalNodes) * 100).toFixed(1) : '0';
      md += `| **${cat.toUpperCase()}** | \`${count}\` | \`${pct}%\` |\n`;
    }
    md += `\n`;

    // 3. Central Architectural Hubs
    md += `## 3. Core Architectural Hubs (Highest Blast Radius If Changed)\n\n`;
    md += `These files are depended upon by the most modules. Any breaking change here cascades across the project.\n\n`;
    md += `| Module Name | Category | Dependents (Consumers) | Internal Imports |\n`;
    md += `| :--- | :--- | :--- | :--- |\n`;
    for (const hub of sortedHubs) {
      md += `| \`${hub.relativePath}\` | \`${hub.category}\` | **${hub.importedBy.length} files** | ${hub.imports.length} files |\n`;
    }
    md += `\n`;

    // 4. Circular Dependencies
    md += `## 4. Circular Dependency Cycles (${activeCycles.length})\n\n`;
    if (activeCycles.length === 0) {
      md += `✅ *No circular dependencies detected. Dependency graph is clean and acyclic.*\n\n`;
    } else {
      md += `> ⚠️ *Circular imports can cause bundler execution order issues and runtime \`undefined\` values.*\n\n`;
      activeCycles.forEach((cycle, idx) => {
        md += `### Cycle #${idx + 1} (${cycle.length} Steps)\n`;
        const readableLoop = cycle.files
          .map((f) => `\`${graph.nodes[f]?.relativePath || f}\``)
          .join(' ➔ ');
        md += `- **Loop Path:** ${readableLoop}\n\n`;
      });
    }

    // 5. Dead Code / Orphan Files
    md += `## 5. Potential Orphan Modules (${activeOrphans.length})\n\n`;
    if (activeOrphans.length === 0) {
      md += `✅ *No orphan files found.*\n\n`;
    } else {
      md += `> 💡 *These files have zero internal consumers. If they are not called dynamically, consider deleting them.*\n\n`;
      md += `| Orphan File | Category | Lines | Size |\n`;
      md += `| :--- | :--- | :--- | :--- |\n`;
      for (const orphan of activeOrphans.slice(0, 15)) {
        md += `| \`${orphan.relativePath}\` | \`${orphan.category}\` | ${orphan.lineCount} LOC | ${(orphan.sizeBytes / 1024).toFixed(1)} KB |\n`;
      }
      if (activeOrphans.length > 15) {
        md += `| *...and ${activeOrphans.length - 15} more orphan files.* | | | |\n`;
      }
      md += `\n`;
    }

    md += `---\n*Generated by [Atlas VS Code Extension](https://github.com/wealthypeople/scope)*\n`;
    return md;
  }
}
